### ISSUE TITLE
hello! this is DrHolsow

### ISSUE THREAD

**Issue by maxmerben** [Mrak-X/Hunspell-Ancient-Greek#1]
dear Mrakia, please let us know how you are! do not do anything drastic. we are really worried.

**Comment by mrakia** [comment]
Hiya, @maxmerben! I’m very surprised to see you here. :)
I had an emotional breakdown lately. That’s a result of the chronic minority stress, I think.

You may find my new contacts in Twitter if you want to.
Good luck and thanks for the message! 💗
